### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [rchorda/covid#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/GNMASD

Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by rchorda** [comment]
Sure, but this data has been simply downloaded from EU official data at Eurostat: https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=demo_r_d2jan&lang=en
filtered to show nuts2 data for Spanish regions.

I will be glad to maintain the data updated and to add any metadata you think it's relevant. But I will need instruction on how to do so.

The notebook graphs the official data the Spanish government shares. The population data is the only static data it uses.
